### ISSUE TITLE
User specified datacube config option is not overridden by the fractional cover application

### ISSUE THREAD

**Issue by santoshamohan** [GeoscienceAustralia/fc#16]
When a user specifies the datacube config file using `-C` option, the `datacube-fc` is not overriding the custom specified datacube config file. However, `datacube-fc` uses default datacube config file from the the environment path where module was loaded.

For ex. 
`datacube-fc submit --app-config /g/data/u46/users/sm9911/FC_ConfigFiles/ls8_fc_albers.yaml -P u46 -q express **-C /g/data/u46/users/sm9911/Datacube_conf.conf** -vv --year 2018`

It is expected that `datacube-fc submit` uses the datacube config file from `/g/data/u46/users/sm9911/Datacube_conf.conf`. However, `datacube-fc` is looking for `datacube.conf` from the default datacube config path.

**Note:** A work around for this issue is to define `DATACUBE_CONFIG_PATH` to point to the custom datacube config file and export `DATACUBE_CONFIG_PATH` variable to the environment path.

**Comment by dunkgray** [comment]
This should be fixed in the latest build (https://github.com/GeoscienceAustralia/fc/commit/457e280cc0513584616f71b7679c185dbc132eff)
