### ISSUE TITLE
Incompatible with numpy >= 1.23.0 as numpy.distutils has been deprecated

### ISSUE THREAD

**Issue by vikineema** [GeoscienceAustralia/fc#57]
See discussion [here](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration)

**Comment by robbibt** [comment]
Hey @emmaai, will this be solved by this PR?
https://github.com/GeoscienceAustralia/fc/pull/56

**Comment by emmaai** [comment]
yes, the pr is targeting this issue
